config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :comments

  get 'login', to: 'sessions#new', as: 'login'
  get 'signup', to: 'users#new', as: 'signup'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user


end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :comments



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      user_id = params[:user_id].to_i
      if user_id == 1 # admin
        user = User.find_by_id(user_id)
        comment = Comment.new
        comment.text = params[:text]
        comment.user = user
        comment.save!
      end

      redirect_to root_url
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        render 'home'
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def edit
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.pass == params[:password]
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def edit
    user = User.find_by_email(params[:id])
    user.email = params[:email]
    user.pass = params[:password]
    user.save

    redirect_to root_url
  end

  def create
    unless User.find_by_email(params[:email])
      user = User.new
      user.email = params[:email]
      user.pass = params[:password]
      user.save
    end

    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/home.erb
<% if current_user %>
  Hola, <%= current_user.email.split('@')[0] %>!
  <%= link_to "Salir", logout_path %>
<% else %>
  <%= link_to "Iniciar sesión", login_path %>
  <%= link_to "Crear cuenta", signup_path, hidden:true %>
<% end %>


<hr>

<% if current_user %>
  <%= form_tag comments_path do |form| %>
    <%= hidden_field_tag :user_id, value=current_user.id %>
    <div class="field">
      <%= label_tag :text, name='Nuevo comentario' %>
      <%= text_field_tag "text", nil, :placeholder => 'Sólo válido para admin' %>
    </div>

    <div class="actions">
      <%= submit_tag "Comentar" %>
    </div>
  <% end %>

  <h3>Comentarios hechos por el admin</h3>
  <ul>
    <% User.find_by_email("admin@admin.com").comments.each do |c| %>
      <li><%= c.text %></li>
    <% end %>
  </ul>

  <% else %>
  <h3>Sólo usuarios registrados pueden ver los comentarios</h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "Home", root_path %>
<hr>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Crear cuenta</h1>

<%= form_tag users_path do |form| %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
  </div>

  <div class="field">
    <%= label_tag :pass %>
    <%= password_field_tag :pass %>
  </div>

  <div class="actions">
    <%= submit_tag "Crear" %>
  </div>
<% end %>